---
- name: Configure NTP Client with Chrony
  hosts: server2
  become: true
  tasks:

    - name: Install Chrony (NTP client)
      package:
        name: chrony
        state: present

    - name: Configure Chrony to use 3.north-america.pool.ntp.org
      template:
        src: chrony_client.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart Chrony

    - name: Enable and Start Chrony Service
      service:
        name: chronyd
        enabled: yes
        state: started
    
    - name: Install Cockpit
      package:
        name: cockpit
        state: present

    - name: Ensure Cockpit is running and enabled
      service:
        name: cockpit
        enabled: yes
        state: started

    - name: Ensure log file exists
      file:
        path: /var/log/automation.log
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Schedule task "runningaway" to log Cockpit status
      cron:
        name: "runningaway"
        minute: "*/5"
        job: "echo \"$(date) - Cockpit Service Status: $(systemctl is-active cockpit)\" >> /var/log/automation.log"


  handlers:
    - name: Restart Chrony
      service:
        name: chronyd
        state: restarted
