---
- name: Create partitions
  hosts: server2
  tasks:
    - name: Create partition
      community.general.filesystem:
        fstype: xfs
        dev: /dev/nvme1n1

    - name: Configure fstab
      ansible.posix.mount:
          path: /extdrive
          src: /dev/nvme1n1
          fstype: xfs
          opts: noatime
          state: present

    - name: lala
      shell: cat /etc/group*

    - name: Configure permissions
      ansible.builtin.file:
          path: /extdrive
          state: directory
          recurse: yes
          group: IT
