---
- name: Create partitions
  hosts: server2
  tasks:
    - name: Install tools
      ansible.builtin.dnf:
        name: parted
        state: present

    - name: Unmount a mounted volume
      ansible.posix.mount:
        path: /extdrive
        state: unmounted

    - name: Create partition
      community.general.parted:
        fs_type: xfs
        device: /dev/nvme1n1
        part_end: 1GiB
        number: 1
        state: present

    - name: Create filesystem 
      community.general.filesystem:
        fstype: xfs
        dev: /dev/nvme1n1

    - shell: ls -l /dev/nvme*
      register: nvme

    - debug:
        msg: "{{ nvme }}"

    - name: Configure fstab
      ansible.posix.mount:
          path: /extdrive
          src: /dev/nvme1n1
          fstype: xfs
          state: mounted

    - shell: mount
      register: mount

    - debug:
        msg: "{{ mount }}"

    - name: Configure permissions
      ansible.builtin.file:
          path: /extdrive
          state: directory
          recurse: yes
          group: IT
