---
- name: Create partitions
  hosts: server2
  tasks:
    - name: Install tools
      ansible.builtin.dnf:
        name: parted
        state: present

    - name: Create partition
      community.general.parted:
        fs_type: xfs
        device: /dev/nvme1n1
        part_end: 1GiB

    - name: Configure fstab
      ansible.posix.mount:
          path: /extdrive
          src: /dev/nvme1n1
          fstype: xfs
          opts: noatime
          state: present

    - shell: mount
      register: mount

    - debug:
        msg: "{{ mount }}"

    - name: Configure permissions
      ansible.builtin.file:
          path: /extdrive
          state: directory
          recurse: yes
          group: IT
