---
- name: ":::: Users and Groups playbook ::::"
  hosts: all
  become: true
  tasks:     
    
    - name: Using users with loop
      ansible.builtin.user:
        name: "{{ item.user }}"
        ssh_key_file: id_rsa
        groups: "{{ item.group }}"
        state: present
      with_items:
        - usr:
            user: Annabelle
            group: Sales
        - usr:
            user: Bob
            group: IT
        - usr:
            user: Carl
            group: Support
        - usr:
            user: Dyson
            group: Evert
        - usr:
            user: Frank
            group: Sales
        - usr:
            user: Gerry
            group: Support
        - usr:
            user: Harold
            group: IT
        - usr:
            user: Isabella
            group: Services
        - usr:
            user: Jameson
            group: Services

  