---
- name: ":::: Users and Groups playbook ::::"
  hosts: all
  become: true
  tasks:     
    
    - name: Using users with loop
      ansible.builtin.user:
        name: "{{ item.user }}"
        ssh_key_file: id_rsa
        groups: "{{ item.group }}"
        state: present
      loop:
        - { user: Annabelle, group: Sales }
        - { user: Bob, group: IT }
        - { user: Carl, group: Support }
        - { user: Dyson, group: Evert }
        - { user: Frank, group: Sales }
        - { user: Gerry, group: Support }
        - { user: Harold, group: IT }
        - { user: Isabella, group: Services }
        - { user: Jameson, group: Services }