---
- name: ":::: Users and Groups playbook ::::"
  hosts: all
  become: true
  tasks:     
    
    - name: Using users with loop
      user:
        user: "{{ item.user }}"
        ssh_key_file: id_rsa
        groups: "{{ item.group }}"
        state: present
      loop:
        user1:
          user: Annabelle
          group: Sales
        user2:
          user: Bob
          group: IT
        user3:
          user: Carl
          group: Support
        user4:
          user: Dyson
          group: Evert
        user5:
          user: Frank
          group: Sales
        user6:
          user: Gerry
          group: Support
        user7:
          user: Harold
          group: IT
        user8:
          user: Isabella
          group: Services
        user9:
          user: Jameson
          group: Services

  